version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    command: >
      tail -f /dev/null
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
