# Generated by Django 5.1.1 on 2024-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('disease_type', models.CharField(blank=True, max_length=100, null=True)),
                ('specific_for_gender', models.CharField(blank=None, max_length=1, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': '01 Diseases',
                'ordering': ['pk'],
            },
        ),
    ]
