# Generated by Django 5.1.1 on 2024-09-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases_core', '0002_diseasetype_alter_disease_disease_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='specific_for_gender',
            new_name='specific_gender',
        ),
    ]
