# Generated by Django 5.1.1 on 2024-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases_core', '0004_alter_disease_options_alter_diseasetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='umls_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
